import './global.css';
import { ThemeToggle } from './components/ThemeToggle';
import React from 'react';
import { NavAuth } from './components/NavAuth';
import Script from 'next/script';

export const metadata = {
  title: 'Avans - Keuzekompas',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Apply stored theme ASAP to avoid flash of wrong theme */}
        <Script id="apply-theme" strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              try {
                var t = localStorage.getItem('kk-theme');
                if (!t && window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
                  t = 'dark';
                }
                if (t === 'dark') document.documentElement.setAttribute('data-theme','dark');
              } catch (_) {}
            `,
          }}
        />
      </head>
      <body>
  <header className="app-header">
          <div className="container app-header-inner">
            <div className="brand">Keuzekompas</div>
            <nav className="nav">
              <a href="/" className="active">Home</a>
              <a href="/modules">Modules</a>
              <a href="/profile">Profiel</a>
              <NavAuth />
              <ThemeToggle />
            </nav>
          </div>
        </header>
        <main className="app-main">
          <div className="container">{children}</div>
        </main>
        <footer className="app-footer">
          <div className="container">© {new Date().getFullYear()} Keuzekompas</div>
        </footer>
      </body>
    </html>
  );
}
