import './global.css';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="app-header">
          <div className="container app-header-inner">
            <div className="brand">Keuzekompas</div>
            <nav className="nav">
              <a href="/" className="active">Home</a>
              <a href="/modules">Modules</a>
            </nav>
          </div>
        </header>
        <main className="app-main">
          <div className="container">{children}</div>
        </main>
        <footer className="app-footer">
          <div className="container">© {new Date().getFullYear()} Keuzekompas</div>
        </footer>
      </body>
    </html>
  );
}
