# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - app-keuzekompas-api-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build API (Nx)
        run: npx nx build api

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: api-dist
          path: dist/apps/api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: api-dist
          path: api-dist

      - name: Show downloaded files (debug)
        run: |
          pwd
          ls -la
          echo "Contents of api-dist:" && ls -la api-dist

      - name: Create deployment archive
        run: |
          set -e
          ROOT="$GITHUB_WORKSPACE"
          DEPLOY_DIR="api-dist"
          if [ -f "$DEPLOY_DIR/main.js" ]; then
            echo "Using $DEPLOY_DIR as deploy root"
          elif [ -f "$DEPLOY_DIR/dist/apps/api/main.js" ]; then
            echo "Using $DEPLOY_DIR/dist/apps/api as deploy root"
            DEPLOY_DIR="$DEPLOY_DIR/dist/apps/api"
          else
            echo "main.js not found at expected locations" >&2
            ls -laR api-dist || true
            exit 1
          fi
          pushd "$DEPLOY_DIR" >/dev/null
          zip -r "$ROOT/api-dist.zip" .
          popd >/dev/null
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E030027D030A4304A06BCE71B53B0E1C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_79F3942891504724AD818180A4A66283 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_066289EEA6AC40408704D2C1C268BA9A }}

      - name: Ensure Node 20 runtime and startup command (optional)
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            set -e
            APP_NAME="app-keuzekompas-api-prod"
            RG="${{ vars.AZURE_RESOURCE_GROUP }}"
            if [ -z "$RG" ]; then
              echo "AZURE_RESOURCE_GROUP not set; skipping runtime configuration."
              exit 0
            fi
            echo "Using resource group: $RG"
            # Set Node stack to 20 LTS
            az webapp config set -g "$RG" -n "$APP_NAME" --linux-fx-version "NODE|20-lts"
            # Set startup command
            az webapp config set -g "$RG" -n "$APP_NAME" --startup-file "node main.js"
            # Also set Node version app setting for good measure
            az webapp config appsettings set -g "$RG" -n "$APP_NAME" --settings WEBSITE_NODE_DEFAULT_VERSION=20

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-keuzekompas-api-prod'
          slot-name: 'Production'
          package: api-dist.zip
          startup-command: 'node main.js'
          